[package]
name = "hello_world"
version = "0.1"
lean_version = "nightly-2018-10-28"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "40fa9ade2f5649569639608db5e621e5fad0cc02"}
